In [1]:
!pip install fastai2 > ../dev/null
!pip install utils > ../dev/null  

In [2]:
from utils import *
from fastai2.vision.widgets import *
from fastai2.vision.all import *

# Lesson 3: Numpy/pytorch, indexing, and broadcasting

In this class, Jeremy showed us how to build a web app using ipywidgets, Binder and Voilà (and a bunch of other amazing services). Those are not tasks for which I can provide you exercises that stand in a notebook. 

So you should follow the great documentations existing out there are try to go live with your MenVsWomen model, for example.

But in the lesson, Jeremy also quickly went through a lot of fundamental concepts of pytorch. In fact he covered so many things so quickly that he decided to shorten the lesson to let you digest all that.

This is the stuff we will be reviewing together.

WARNING: this is stuff that you probably don't need if you are just following FAST.AI to acquire general knowledge of how things work. This is more for future practitionners/researchers ;) 

# Numpy and Pytorch
Numpy and Pytorch are pretty similar in how they behave. We'll first learn a few cools tricks with Numpy, and you'll see that you can transfer most of them to pytorch ;)

## Indexing

In [3]:
# Let's say we have a list of numbers:
my_list = [1, 2, 3, 4, 5]
my_list

[1, 2, 3, 4, 5]

In [4]:
# And let's say you wanted to grab the first and last element of that list 
try:
    print(my_list[0, 5])
except:
    print("passing O, 5 didn't work")

try:
    print(my_list[[0, 5]])
except:
    print("passing [O, 5] didn't work")


# Note: if you don't know how try works, well, that pretty much does what its name
# says: it tries to do something, and if that doesn't work, it does the "except"

passing O, 5 didn't work
passing [O, 5] didn't work


In [0]:
# your turn: try to figure out a way to get the first and last element of that list



# Not easy right ?

In [6]:
# With numpy, you can do that kind of "indexing" very easily:
my_array = array(my_list)

# Try the two approaches I tried with the list above to see which one works ;)
print(my_array[      ])  # Fill in the blank

[1 5]


In [10]:
# Numpy arrays also come with cool methods that python lists don't have:
print(my_array.sum())
print(my_array.mean())
print(my_array.std())

15
3.0
1.4142135623730951


### Interlude -  compare two classes:
Compare two groups of students:

In [0]:
group_a_grades = array([10, 10, 10, 10, 11, 11, 11, 11, 9, 9, 9, 9])
group_b_grades = array([0, 5, 5, 5, 10, 10, 10, 10, 15, 15, 15, 20])

# What's the average grade of group_a :
group_a_mean = group_a_grades.____()
assert group_a_mean == 10

In [0]:
# And what's the average grade of group_b ?
group_b_mean = __________________
assert group_b_mean == 10

These two groups of students have the same average grades, so they must be similar right ?

In [0]:
# Let's see, what's the standard deviations of their grades ? 
group_a_std = group_a_grades.___()
assert abs(group_a_std - 0.8164) < 0.5
group_b_std = ____________________
assert abs(group_b_std - 5.4) < 0.5

print(group_a_std, group_b_std)

# Really not the same groups in the end ;-)
# Always check the std: you could have two countries with the same mean wage
# and still have one of the two much more unequal than the second

# Bonus: what's an image with a standard deviation of all the pixels of 0 ?
# ______________    # check the notebook solution for answer ;) 

0.816496580927726 5.400617248673217


### Shape
Another VERY important method is shape. It will tell you how many axis your array/tensor has:

In [12]:
my_scalar = array([1])
print(my_scalar.shape)

print("Compare this: ")
my_vector = array([1, 2])
print(my_vector.shape)

print("To this: ")
my_vector = array([[1, 2]])
print(my_vector.shape, ': 1 row, two columns')
print("Can you see the difference that adding an extra pair of brackets make ? ")

(1,)
Compare this: 
(2,)
To this: 
(1, 2) : 1 row, two columns
Can you see the difference that adding an extra pair of brackets make ? 


In [0]:
my_matrix = array([ [1, 2, 3], [4, 5, 5]])
print(my_matrix)
print(my_matrix______, ': _ rows, _ columns')  # Complete this line

[[1 2 3]
 [4 5 5]]
(2, 3) : 2 rows, 3columns


## Bigger arrays

In [13]:
# Things become even more interesting when you have not a list,
# but an array of numbers:

my_list_of_lists = [[1, 2, 3], 
                    [4, 5, 6], 
                    [7, 8, 9]]
my_matrix = array(my_list_of_lists)
my_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
# Let's say you only care about the third row; using what you've learned above
# and in the course, figure out a way to get the 3rd row by indexing into my_array:

test =  my_matrix[_____] # be careful, python's indexing starts at 0 ;-)
assert (test == [7, 8, 9]).all()

In [0]:
# Now, you want the third row, second and third column (8 and 9):

test = my_matrix[______]
assert (test == [8, 9]).all()

In [0]:
# now, you want the top-left square (1,2; 4,5):

test = my_matrix[________]
assert (test == [[1, 2], [4, 5]]).all()

In [0]:
# You might not see why practicing this is important...
# but trust me, it will pay off down the road ;-)

## Broadcasting

In [0]:
# Another cool (and very powerful) trick is broadcasting.
# As seen in the course, you can replace

my_array = array([1, 2, 3])
print(my_array * array([2, 2, 2]))

#by:
print(my_array * 2)

[2 4 6]
[2 4 6]


In [0]:
# Let's re-use my_matrix; try to multiply every number in it by 3:
test = my_matrix _ _ 

answer = array([[3, 6, 9],
 [12, 15, 18],
 [21, 24, 27]])
assert (test == answer).all()

In [0]:
# Jargon note: you'll oftentimes encounter the word "scalar". It just means "a single number"
# So far, we've done operations on a matrix using only one number (a.k.a a "scalar")
# What if we wanted to multiply only the third column by 3 ?
# We could pass a vector of three numbers: 1, 1, and 3. Let's try:

test = my_matrix * ________ 

answer = array([[ 1,  2,  9],
       [ 4,  5, 18],
       [ 7,  8, 27]])

assert (test == answer).all()

In [0]:
# Harder stuff: now, try to multiply only the third column by 3: 
# If you don't know where to start, I provide a hint in the cell below


test = my_matrix * array(_______________)

answer = array([[ 1,  2,  3],
       [ 4,  5,  6],
       [21, 24, 27]])

assert (test == answer).all()

In [14]:
# Hint: if you construct your array like this, it prints as a line
my_array = array([1, 1, 3])
print(my_array)

[1, 1, 3]


In [15]:
# How would could you make it display as a column like so ? 
# If you figure this out, you should be able to answer the question above ;)

array([[1],
       [1],
       [3]])

In [0]:
# Now that you've figured it out, I'll teach you a good trick to do that more easily :
my_array = array([1, 1, 3])
my_array[:, None]

# Note: this is a pretty advanced trick that most numpy/pytorch users don't know
# The None adds an extra axis to your tensor/array where you put it in your indexing 

array([[1],
       [1],
       [3]])

### The transpose method
Transpose takes a matrix and pivots it on it's diagonal axis. For lack of a better description, let's see an example: 

In [16]:
my_matrix = array([[1, 2, 3],
       [4, 5, 5]])

my_matrix

array([[1, 2, 3],
       [4, 5, 5]])

In [17]:
my_matrix.T

array([[1, 4],
       [2, 5],
       [3, 5]])

In other words, rows become columns, and vice versa

In [0]:
# Funky advanced exercise: feel free to skip :-)
# my array looks like this: array([1, 1, 3])
print(my_array)
print(my_array.shape, ' just three numbers')
# As such, it just has 3 numbers, no rows and columns
# So transposing it won't do much: 
print('transposed:', my_array.T)

[1 1 3]
(3,)  just three numbers
transposed: [1 1 3]


In [0]:
# If, however, you use the technique of indexing with "None" that I showed above,
# you can make it have one row, three columns
# Let's try:
test = my_array[_______]
assert test.shape == (1, 3)

In [0]:
# Now try to take the transpose of test: 
____._
# Voilà ;-) 

array([[1],
       [1],
       [3]])

Note: if you've been working on this notebook without interruption since the beginning of it, now is a good time to take a break to let the material sink in ;-) 

# Matrix-Matrix multiplication 

In [0]:
# WARNING: this stuff is pretty involved. It's okay if you don't get everything at first
# I had to do a lot of exercises to get this stuff right. 
# But when you'll have it drilled, it will save you plenty of time down the road

# Once again, if you are an executive or something and don't need the nitty-gritty details
# of how all this works, this is way too much, feel free to skip the notebook ;) 

If you never saw matrix-matrix multiplication before or need a refresher, please take a look at <a href="http://matrixmultiplication.xyz/">this link </a>

Let's say we want to reproduce the following equation: 

\begin{equation}\left[\begin{array}{ll}
1 & 2 \\
0 & 1
\end{array}\right]\left[\begin{array}{ll}
2 & 5 \\
6 & 7
\end{array}\right]=\left[\begin{array}{ll}
14 & 19 \\
6 & 7
\end{array}\right]\end{equation}


------Linear algebra refresher------

----First row result----

1 * 2 + 2 * 6 = 2 + 12 = 14

1 * 5 + 2 * 7 = 5 + 14 = 19

----Second row result----

0 * 2 + 1 * 6 = 0 + 6 = 6 

0 * 5 + 1 * 7 = 0 + 7 = 7



In [18]:
# How would you do that with broadcasting ? 
matrix_one = array([[1, 2], [0, 1]])
matrix_two = array([[2, 5], [6, 7]])

# First, try to use the multiplication sign (the star), in python
result = __________ _ __________
print(result)

# Doesn't look good... this performs element-wise multiplication

[[ 2 10]
 [ 0  7]]


In [0]:
# But now, you know that you can use numpy to multiply a line by a column right ? 
# How would you, for example, multiply [1 2] by [2 6] to obtain the 14 ? 
slice_matrix_one = matrix_one[____]  # get the [1 2]
slice_matrix_two = matrix_two[____] # get the [2 6]

assert (slice_matrix_one == array([1, 2])).all()
assert (slice_matrix_two == array([2, 6])).all()

In [0]:
# Well, 2 + 12 = 14, but we have one step left....
slice_matrix_one * slice_matrix_two

array([ 2, 12])

In [0]:
# Can you figure out how to do it ? 
# if not, re-read this notebook, the answer is somewhere above ;-)
result = (slice_matrix_one * slice_matrix_two)____  # complete this line
assert result == 14

Now, to go further, let's use broadcasting to multiply the first row by the entire matrix_two:

In [0]:
matrix_one[0] * matrix_two.T

array([[ 2, 12],
       [ 5, 14]])

As you can see, summing over the first row will give you 14, and over the second 19

If you don't get why we used the transpose, go again to http://matrixmultiplication.xyz/ and look what it does with the individual columns of the second matrix ;-)

In [0]:
# But how can we sum over only one row at a time ? 
print(".sum() alone doesn't work:")
(matrix_one[0] * matrix_two.T).sum() 

.sum() alone doesn't work:


33

In [0]:
# Here is one neat trick:
example_matrix = array([[1,2,3], [4,5,6]])
print(example_matrix)
print('-'*10)
print('', example_matrix.sum(0))

[[1 2 3]
 [4 5 6]]
----------
 [5 7 9]


In [0]:
# I just took the sum of example_matrix over each column 
# what could you change to make it sum over each row ? 
result = (matrix_one[0] * matrix_two.T).sum(_) 

assert (result == array([14, 19])).all()

array([14, 19])

In [0]:
# So now, all you have to do is do this for each column and row:
result = np.zeros([2, 2])

for i, row in enumerate(matrix_one):
    result[i] = (___ * __________._).___(_)
result

array([[14., 19.],
       [ 6.,  7.]])

# Why bother with this ? 
broadcasting is very powerful. If we were to do matrix-matrix multiplication using classic python with only for loops, here is how we would do it:

In [0]:
# Note: this code snippet is taken from last year part 2 of the course:
def matmul(a,b):
    ar,ac = a.shape # n_rows * n_cols
    br,bc = b.shape
    assert ac==br
    c = torch.zeros(ar, bc)
    for i in range(ar):
        for j in range(bc):
            for k in range(ac): # or br
                c[i,j] += a[i,k] * b[k,j]
    return c

In [0]:
# Let's take two 5by5 matrices:
m1 = torch.randn(5, 5)
m2 = torch.randn(5, 5)

In [0]:
%%timeit
matmul(m1, m2)

100 loops, best of 3: 3.43 ms per loop


In [0]:
# Now, let's try again with broadcasting:
def matmul(a,b):
    ar,ac = a.shape
    br,bc = b.shape
    assert ac==br
    c = torch.zeros(ar, bc)
    for i in range(ar):  # note that we removed two for loops
        c[i]   = (a[i  ].unsqueeze(-1) * b).sum(dim=0)
    return c

In [0]:
%%timeit
matmul(m1, m2)

The slowest run took 15.43 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 117 µs per loop


We went down from miliseconds to microseconds! that's more than 1000 times faster ! 

<blockquote> "Well, okay, but I'll probably never write matrix multiplications myself, so what's the point ?" </blockquote>

## Why bother with this (2) ?

That's true, but here is another example of how being good at tensor/arrays manipulation can help you:

- Suppose you have <a href='https://www.kaggle.com/c/rsna-intracranial-hemorrhage-detection'>600 000 images of brain CT scans</a>.
- using show_batch, you realize one is fully black !
- that could screw your model, so you want to remove all the images that are all black. How could you do that ?

In [0]:
my_screwed_ct_brainscan = torch.zeros([3, 800, 800])  # three channels, 800x800 images
my_screwed_ct_brainscan.shape

torch.Size([3, 800, 800])

Well, if you have paid attention to the "assert" test I create in the cells you have to complete, you'll have noticed that I use the .all() method.

What does it do ?

In [0]:
my_screwed_ct_brainscan == 0 

tensor([[[True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         ...,
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True]],

        [[True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         ...,
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True]],

        [[True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         ...,
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True]]]

Above, I am using broadcasting to check whether <b>each individual pixel</b> of my ct_scan == 0 (I compare a tensor to a single scalar: broadcasting again). Problem, there are 3 * 800 * 800 pixels:

In [0]:
3 * 800 * 800 

1920000

So manually checking  1 920 000 pixels to see whether they are true doesn't seem really practical right ? 

Enters .all():


In [0]:
# This will return True only if ALL the pixels satisfy the condition: 
(my_screwed_ct_brainscan == 0 ).all()

tensor(True)

Here, I created the picture myself, so we knew it was only zeroes all along.

But this approach helped me iterate through 600 000 images with a little for loop in less than 20 minutes and clean my dataset. Some other tricks like that helped me secure a 84th place in the ranking, thus rewarding me with a Kaggle bronze medal ;)

That being said, I am open to suggestions. If you think this notebook is too heavy for beginners, feel free to provide your feedback in the forums ;)